- name: "openrouter/openai/gpt-4o"
  edit_format: "diff"
  weak_model_name: "openrouter/meta-llama/llama-3.2-11b-vision-instruct"
  use_repo_map: true
  send_undo_reply: true
  lazy: true
  reminder: false
  examples_as_sys_msg: true

- name: "github/gpt-4o"
  edit_format: "diff"
  weak_model_name: "github/gpt-4o"
  use_repo_map: true
  send_undo_reply: true
  lazy: true
  reminder: false
  examples_as_sys_msg: true

- name: "openrouter/anthropic/claude-3.5-sonnet"
  edit_format: "diff"
  weak_model_name: "openrouter/meta-llama/llama-3.2-11b-vision-instruct"
  use_repo_map: true
  examples_as_sys_msg: true
  reminder: false
  examples_as_sys_msg: true

- name: "openrouter/deepseek/deepseek-coder"
  edit_format: "diff"
  weak_model_name: "openrouter/meta-llama/llama-3.2-11b-vision-instruct"
  use_repo_map: true
  send_undo_reply: true
  reminder: false
  examples_as_sys_msg: true

- name: "openrouter/deepseek/deepseek-chat"
  edit_format: "diff"
  weak_model_name: "openrouter/meta-llama/llama-3.2-11b-vision-instruct"
  use_repo_map: true
  send_undo_reply: true
  reminder: false
  examples_as_sys_msg: true

- name: "openrouter/meta-llama/llama-3.1-8b-instruct"
  edit_format: "diff"
  weak_model_name: "openrouter/meta-llama/llama-3.1-8b-instruct"
  use_repo_map: false
  send_undo_reply: false
  lazy: false
  reminder: false
  examples_as_sys_msg: true

- name: "openrouter/meta-llama/llama-3.2-11b-vision-instruct"
  edit_format: "diff"
  weak_model_name: "openrouter/meta-llama/llama-3.2-11b-vision-instruct"
  use_repo_map: false
  send_undo_reply: false
  lazy: false
  reminder: false
  examples_as_sys_msg: true

- name: "openrouter/qwen/qwen-2.5-coder-32b-instruct"
  edit_format: "diff"
  weak_model_name: "openrouter/meta-llama/llama-3.2-11b-vision-instruct"
  use_repo_map: true
  send_undo_reply: true
  reminder: false
  examples_as_sys_msg: true
